databases:
  - name: minieasyhygor
    databaseName: minieasyhygor
    user: minieasyhygor_user
    plan: free

services:
  - type: web
    name: minieasyhygor-backend
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: minieasyhygor
          property: connectionString
      - key: DEVISE_JWT_SECRET_KEY
        value: "62ac646428a87524fb610baf09e343f4b219d10499ba665a95a3aaf1b5924f3d94b3e1e92a714461152fc897ad7bfe39ec0025f39ab3744813a8a68b3ccb73ca"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"

  - type: web
    name: minieasyhygor-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run serve